{
   "AWSTemplateFormatVersion":"2010-09-09",
   "Description":"CloudFormation Template for EC2 -> Kinesis -> Lambda -> SNS -> DynamoDB",
   "Resources":{
      "MyKinesisStream":{
         "Type":"AWS::Kinesis::Stream",
         "Properties":{
            "Name":"MyKinesisStream",
            "ShardCount":1
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"0d39e8dd-76fb-4e11-b0b5-22f72f58e30a"
            }
         }
      },
      "MyEC2Role":{
         "Type":"AWS::IAM::Role",
         "Properties":{
            "AssumeRolePolicyDocument":{
               "Version":"2012-10-17",
               "Statement":[
                  {
                     "Effect":"Allow",
                     "Principal":{
                        "Service":"ec2.amazonaws.com"
                     },
                     "Action":"sts:AssumeRole"
                  }
               ]
            },
            "Policies":[
               {
                  "PolicyName":"KinesisAccessPolicy",
                  "PolicyDocument":{
                     "Version":"2012-10-17",
                     "Statement":[
                        {
                           "Effect":"Allow",
                           "Action":[
                              "kinesis:PutRecord",
                              "kinesis:PutRecords",
                              "kinesis:DescribeStream",
                              "kinesis:*"
                           ],
                           "Resource":{
                              "Fn::GetAtt":[
                                 "MyKinesisStream",
                                 "Arn"
                              ]
                           }
                        }
                     ]
                  }
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"a2a297b8-58e3-4f57-951c-29f3ca549f1e"
            }
         }
      },
      "MyInstanceProfile":{
         "Type":"AWS::IAM::InstanceProfile",
         "Properties":{
            "Roles":[
               {
                  "Ref":"MyEC2Role"
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"34fe417a-4ea9-4ec2-a0ef-ab400af2c030"
            }
         }
      },
      "MyVPC":{
         "Type":"AWS::EC2::VPC",
         "Properties":{
            "CidrBlock":"10.0.0.0/16",
            "EnableDnsSupport":"true",
            "EnableDnsHostnames":"true",
            "Tags":[
               {
                  "Key":"Name",
                  "Value":"MyVPC"
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"7761faaf-3c80-4d06-995f-9c3ac776ea26"
            }
         }
      },
      "MyInternetGateway":{
         "Type":"AWS::EC2::InternetGateway",
         "Properties":{
            "Tags":[
               {
                  "Key":"Name",
                  "Value":"MyInternetGateway"
               }
            ]
         }
      },
      "AttachGateway":{
         "Type":"AWS::EC2::VPCGatewayAttachment",
         "Properties":{
            "VpcId":{
               "Ref":"MyVPC"
            },
            "InternetGatewayId":{
               "Ref":"MyInternetGateway"
            }
         }
      },
      "MyPublicSubnet":{
         "Type":"AWS::EC2::Subnet",
         "Properties":{
            "VpcId":{
               "Ref":"MyVPC"
            },
            "CidrBlock":"10.0.0.0/24",
            "AvailabilityZone":"ap-south-1a",
            "MapPublicIpOnLaunch":"true",
            "Tags":[
               {
                  "Key":"Name",
                  "Value":"MyPublicSubnet"
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"fafdf581-6331-44bb-8222-2c784fe57808"
            }
         }
      },
      "MySecurityGroup":{
         "Type":"AWS::EC2::SecurityGroup",
         "Properties":{
            "GroupDescription":"Allow SSH and HTTP access",
            "VpcId":{
               "Ref":"MyVPC"
            },
            "SecurityGroupIngress":[
               {
                  "IpProtocol":"tcp",
                  "FromPort":"22",
                  "ToPort":"22",
                  "CidrIp":"0.0.0.0/0"
               },
               {
                  "IpProtocol":"tcp",
                  "FromPort":"80",
                  "ToPort":"80",
                  "CidrIp":"0.0.0.0/0"
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"88f5b20d-88bc-4087-a829-3d173078dd28"
            }
         }
      },
      "MyKeyPair":{
         "Type":"AWS::EC2::KeyPair",
         "Properties":{
            "KeyName":"my-key-pair",
            "PublicKeyMaterial":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCZJD5yBDOCCYvOulCxmzNdw22p2X/hXRfnNbH/J2svz78rf3hp+pCvbPTj2OZaVc4dLu41g3iuN1lRc3fneppmH/cOSzUeMDKBj5eJLoBs4S/uXisk1T2H9peQCj0OTxkENEWBs6g74+t5hW5EgimjKrkRwFuDJlb91maxSFItE6t8ADF7McNbo7s3NWzEUSnxRerQxbBah/xDLcpCb61R6BBn+YO6Z5RYfH5fBRXlKiDj3s0JqIkxdd3p7s5XzAfxTlGaa9NZw3iITYxp44RaaQqN+olmv2/sLPe2NEmE8CV4IJ9Q+txQjI2LxEjwYtMhpbREOAf+dZWZP7auqNVTs0ATwLw6fVhzVbVPccNJHae+eUMiB1cn1LlML2ElhunPYK+c52s+C3IBFAaYLkxkOOtBuUHas3T23cA+Qnie2b6sKZa8iGkcJsPAKlTwNcYc9SBFpC4gO8hbO48oS053oRg/ZUNpUp8rk1nYZfmTFXxa8Z2oRZ9ix3U4/6WRj5k= cloud-formation"
      },
      "MyEC2Instance":{
         "Type":"AWS::EC2::Instance",
         "Properties":{
            "InstanceType":"t2.micro",
            "SecurityGroupIds":[
               {
                  "Fn::GetAtt":[
                     "MySecurityGroup",
                     "GroupId"
                  ]
               }
            ],
            "SubnetId":{
               "Ref":"MyPublicSubnet"
            },
            "IamInstanceProfile":{
               "Ref":"MyInstanceProfile"
            },
            "KeyName":{
               "Ref":"MyKeyPair"
            },
            "ImageId":"ami-06f621d90fa29f6d0",
            "Tags":[
               {
                  "Key":"Name",
                  "Value":"MyEC2Instance"
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"ce92bd22-cd1c-4500-be08-fd4b9c0b0580"
            }
         }
      },
      "MyLambdaFunction":{
         "Type":"AWS::Lambda::Function",
         "Properties":{
            "Handler":"index.handler",
            "Role":{
               "Fn::GetAtt":[
                  "MyLambdaRole",
                  "Arn"
               ]
            },
            "FunctionName":"MyLambdaFunction",
            "Code":{
               "S3Bucket":"aloo123",
               "S3Key":"test.zip"
            },
            "Runtime":"python3.8"
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"f101f355-1d94-41b8-aaa1-bc23d62cde95"
            }
         }
      },
      "MyLambdaRole":{
         "Type":"AWS::IAM::Role",
         "Properties":{
            "AssumeRolePolicyDocument":{
               "Version":"2012-10-17",
               "Statement":[
                  {
                     "Effect":"Allow",
                     "Principal":{
                        "Service":"lambda.amazonaws.com"
                     },
                     "Action":"sts:AssumeRole"
                  }
               ]
            },
            "Policies":[
               {
                  "PolicyName":"KinesisAccessPolicy",
                  "PolicyDocument":{
                     "Version":"2012-10-17",
                     "Statement":[
                        {
                           "Effect":"Allow",
                           "Action":[
                              "kinesis:GetRecords",
                              "kinesis:GetShardIterator",
                              "kinesis:DescribeStream",
                              "kinesis:ListStreams"
                           ],
                           "Resource":"*"
                        }
                     ]
                  }
               },
               {
                  "PolicyName":"SNSPublishPolicy",
                  "PolicyDocument":{
                     "Version":"2012-10-17",
                     "Statement":[
                        {
                           "Effect":"Allow",
                           "Action":[
                              "sns:Publish"
                           ],
                           "Resource":"*"
                        }
                     ]
                  }
               }
            ]
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"3427ff4b-6437-42cd-ae11-d46ddf09fc40"
            }
         }
      },
      "MySNSTopic":{
         "Type":"AWS::SNS::Topic",
         "Properties":{
            "DisplayName":"My SNS Topic"
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"7b28736f-dc80-4523-8fb2-84c6cc954341"
            }
         }
      },
      "MyDynamoDBTable":{
         "Type":"AWS::DynamoDB::Table",
         "Properties":{
            "TableName":"MyDynamoDBTable",
            "AttributeDefinitions":[
               {
                  "AttributeName":"ID",
                  "AttributeType":"S"
               }
            ],
            "KeySchema":[
               {
                  "AttributeName":"ID",
                  "KeyType":"HASH"
               }
            ],
            "ProvisionedThroughput":{
               "ReadCapacityUnits":5,
               "WriteCapacityUnits":5
            }
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"88a3db45-3f48-4fe3-8249-c0574298f7b3"
            }
         }
      },
      "MyLambdaInvokePermission":{
         "Type":"AWS::Lambda::Permission",
         "Properties":{
            "Action":"lambda:InvokeFunction",
            "FunctionName":{
               "Fn::GetAtt":[
                  "MyLambdaFunction",
                  "Arn"
               ]
            },
            "Principal":"sns.amazonaws.com",
            "SourceArn":{
               "Ref":"MySNSTopic"
            }
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"ac6a2086-9630-4349-84f0-6b13745e15e2"
            }
         }
      },
      "MyKinesisEventSourceMapping":{
         "Type":"AWS::Lambda::EventSourceMapping",
         "Properties":{
            "BatchSize":10,
            "EventSourceArn":{
               "Fn::GetAtt":[
                  "MyKinesisStream",
                  "Arn"
               ]
            },
            "FunctionName":{
               "Fn::GetAtt":[
                  "MyLambdaFunction",
                  "Arn"
               ]
            },
            "StartingPosition":"TRIM_HORIZON"
         },
         "Metadata":{
            "AWS::CloudFormation::Designer":{
               "id":"c40fe520-6602-4c7a-868f-102aff196fa3"
            }
         }
      },
      "MyRouteTable": {
         "Type": "AWS::EC2::RouteTable",
         "Properties": {
            "VpcId": { "Ref": "MyVPC" }
         }
      },
      "MyRoute": {
         "Type": "AWS::EC2::Route",
         "DependsOn": "AttachGateway",
         "Properties": {
            "RouteTableId": { "Ref": "MyRouteTable" },
            "DestinationCidrBlock": "0.0.0.0/0",
            "GatewayId": { "Ref": "MyInternetGateway" }
         }
      }
   },
   "Outputs":{
      "InstanceId":{
         "Description":"EC2 Instance ID",
         "Value":{
            "Ref":"MyEC2Instance"
         }
      }
   },
   "Metadata":{
      "AWS::CloudFormation::Designer":{
         "88a3db45-3f48-4fe3-8249-c0574298f7b3":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":270,
               "y":390
            },
            "z":1,
            "embeds":[

            ]
         },
         "7b28736f-dc80-4523-8fb2-84c6cc954341":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":390,
               "y":390
            },
            "z":1,
            "embeds":[

            ]
         },
         "3427ff4b-6437-42cd-ae11-d46ddf09fc40":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":510,
               "y":390
            },
            "z":1,
            "embeds":[

            ]
         },
         "f101f355-1d94-41b8-aaa1-bc23d62cde95":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":270,
               "y":510
            },
            "z":1,
            "embeds":[

            ]
         },
         "ac6a2086-9630-4349-84f0-6b13745e15e2":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":390,
               "y":510
            },
            "z":1,
            "embeds":[

            ]
         },
         "7761faaf-3c80-4d06-995f-9c3ac776ea26":{
            "size":{
               "width":240,
               "height":240
            },
            "position":{
               "x":360,
               "y":90
            },
            "z":1,
            "embeds":[
               "88f5b20d-88bc-4087-a829-3d173078dd28"
            ]
         },
         "88f5b20d-88bc-4087-a829-3d173078dd28":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":390,
               "y":150
            },
            "z":2,
            "parent":"7761faaf-3c80-4d06-995f-9c3ac776ea26",
            "embeds":[

            ],
            "iscontainedinside":[
               "7761faaf-3c80-4d06-995f-9c3ac776ea26"
            ]
         },
         "594651a3-ed72-4d7c-84f1-3ca360d38e4a":{
            "size":{
               "width":150,
               "height":150
            },
            "position":{
               "x":60,
               "y":390
            },
            "z":1,
            "embeds":[

            ]
         },
         "fafdf581-6331-44bb-8222-2c784fe57808":{
            "size":{
               "width":240,
               "height":240
            },
            "position":{
               "x":60,
               "y":90
            },
            "z":1,
            "embeds":[
               "ce92bd22-cd1c-4500-be08-fd4b9c0b0580"
            ]
         },
         "ce92bd22-cd1c-4500-be08-fd4b9c0b0580":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":90,
               "y":150
            },
            "z":2,
            "parent":"fafdf581-6331-44bb-8222-2c784fe57808",
            "embeds":[

            ],
            "isassociatedwith":[
               "MyEC2Instance"
            ]
         },
         "7768264a-badd-4294-9943-56666dd6a790":{
            "size":{
               "width":240,
               "height":240
            },
            "position":{
               "x":60,
               "y":270
            },
            "z":1,
            "embeds":[
               "fda8ae1a-4059-40c5-96e9-e893fc9c55f2"
            ]
         },
         "fda8ae1a-4059-40c5-96e9-e893fc9c55f2":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":90,
               "y":330
            },
            "z":2,
            "parent":"7768264a-badd-4294-9943-56666dd6a790",
            "embeds":[

            ],
            "iscontainedinside":[
               "7768264a-badd-4294-9943-56666dd6a790"
            ]
         },
         "0d39e8dd-76fb-4e11-b0b5-22f72f58e30a":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":0,
               "y":150
            },
            "z":2,
            "parent":"594651a3-ed72-4d7c-84f1-3ca360d38e4a",
            "embeds":[

            ],
            "iscontainedinside":[
               "594651a3-ed72-4d7c-84f1-3ca360d38e4a"
            ]
         },
         "34fe417a-4ea9-4ec2-a0ef-ab400af2c030":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":270,
               "y":330
            },
            "z":1,
            "embeds":[

            ]
         },
         "a2a297b8-58e3-4f57-951c-29f3ca549f1e":{
            "size":{
               "width":60,
               "height":60
            },
            "position":{
               "x":180,
               "y":150
            },
            "z":2,
            "parent":"7768264a-badd-4294-9943-56666dd6a790",
            "embeds":[

            ],
            "iscontainedinside":[
               "7768264a-badd-4294-9943-56666dd6a790"
            ]
         }
      }
   }
}
